export const PACKAGE_NAME = '@hardmachinelabs/index-ai-validator'

export const CLI_NAME = 'index-ai'

export const SCHEMA_VERSION = '0.1'

export const DEFAULT_TIMEOUT_MS = 10_000

export const DEFAULT_MAX_CONCURRENCY = 5

export const MANIFEST_CANONICAL_PATH = '/.well-known/index-ai.json'

export const MANIFEST_FALLBACK_PATH = '/index-ai.json'

export const CHECK = {
  L1_MANIFEST_FOUND: 'L1_MANIFEST_FOUND',
  L1_MANIFEST_CONTENT_TYPE: 'L1_MANIFEST_CONTENT_TYPE',
  L1_MANIFEST_JSON_VALID: 'L1_MANIFEST_JSON_VALID',
  L1_MANIFEST_SCHEMA_VALID: 'L1_MANIFEST_SCHEMA_VALID',
  L1_DOMAIN_MATCH: 'L1_DOMAIN_MATCH',
  L1_FALLBACK_MATCH: 'L1_FALLBACK_MATCH',

  L2A_SHADOW_DECLARED: 'L2A_SHADOW_DECLARED',
  L2A_SHADOW_FOUND: 'L2A_SHADOW_FOUND',
  L2A_SHADOW_CONTENT_TYPE: 'L2A_SHADOW_CONTENT_TYPE',
  L2A_SHADOW_JSON_VALID: 'L2A_SHADOW_JSON_VALID',
  L2A_SHADOW_SCHEMA_VALID: 'L2A_SHADOW_SCHEMA_VALID',
  L2A_NO_PAGES_ARRAY: 'L2A_NO_PAGES_ARRAY',
  L2A_TOTAL_NODES_MATCH: 'L2A_TOTAL_NODES_MATCH',
  L2A_NODE_REQUIRED_FIELD: 'L2A_NODE_REQUIRED_FIELD',
  L2A_NODE_LLM_URL_REQUIRED: 'L2A_NODE_LLM_URL_REQUIRED',
  L2A_NODE_CONTENT_CHARS_REQUIRED: 'L2A_NODE_CONTENT_CHARS_REQUIRED',
  L2A_NODE_CONTENT_CHARS_MODE_REQUIRED: 'L2A_NODE_CONTENT_CHARS_MODE_REQUIRED',
  L2A_LLM_URL_PROTOCOL: 'L2A_LLM_URL_PROTOCOL',
  L2A_LLM_URL_FETCH: 'L2A_LLM_URL_FETCH',
  L2A_LLM_URL_CONTENT_TYPE: 'L2A_LLM_URL_CONTENT_TYPE',
  L2A_LLM_URL_HTML_LEAK: 'L2A_LLM_URL_HTML_LEAK',
  L2A_CONTENT_CHARS_EXACT_MATCH: 'L2A_CONTENT_CHARS_EXACT_MATCH',
  L2A_CONTENT_CHARS_MAX_VALID: 'L2A_CONTENT_CHARS_MAX_VALID',
  L2A_SUMMARY_LENGTH: 'L2A_SUMMARY_LENGTH',
  L2A_PROMPT_INJECTION_PATTERN: 'L2A_PROMPT_INJECTION_PATTERN',

  DISCOVERY_HTML_LINK: 'DISCOVERY_HTML_LINK',
  DISCOVERY_ROBOTS_AI_INDEX: 'DISCOVERY_ROBOTS_AI_INDEX',
  DISCOVERY_LLMS_TXT_BRIDGE: 'DISCOVERY_LLMS_TXT_BRIDGE',
  DISCOVERY_LLMS_TXT_CONTENT_TYPE: 'DISCOVERY_LLMS_TXT_CONTENT_TYPE',
  DISCOVERY_HTTP_LINK_HEADER: 'DISCOVERY_HTTP_LINK_HEADER',

  HTTP_NETWORK_ERROR: 'HTTP_NETWORK_ERROR',
  HTTP_PRIVATE_HOST_BLOCKED: 'HTTP_PRIVATE_HOST_BLOCKED',

  SEC_SECRET_PATTERN: 'SEC_SECRET_PATTERN',
  SEC_PRIVATE_INFRA_PATTERN: 'SEC_PRIVATE_INFRA_PATTERN',
} as const
